Debug render warnings, delete console.logs
fitness-tailor/fitness-tailor-client pull request #51
Opened 2020-11-10 20:53 UTC by kokosaka

2020-11-10 23:46 UTC, riz671 approved these changes

2020-11-11 00:32 UTC, kokosaka commented
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-10 at 16 32 18](https://user-images.githubusercontent.com/63432172/98750250-50933280-2372-11eb-8843-1a5c17ed1172.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-10 at 16 32 15](https://user-images.githubusercontent.com/63432172/98750252-54bf5000-2372-11eb-97ab-fd6169e371fd.png)

2020-11-11 00:35 UTC, riz671 commented on screens/ProfileScreen.js
> +  const goalList = [
Bloody Brilliant

2020-11-11 00:37 UTC, riz671 commented on screens/HomeScreen.js
> +      Object.values(snapshot.val()).map((recipe) => {
Neat!

2020-11-11 00:47 UTC, riz671 requested changes
Fix the use Effect and you should be good!

2020-11-11 00:47 UTC, riz671 commented on screens/HomeScreen.js
> +  })
This use effect is unoptimized. Right now, the useEffect runs EVERYTIME an update happens, which can be taxing to the system by causing muliple re-renders if something changes in homescreen. I change profile picture, BOOM, use effect runs again. I click log out, state changes, BOOM, use effect runs again. What we want is to update once user is retrieved.

You fix that is by adding an array of values as the second argument of useEffect such that we don't re-render page unneccesarily. add [props.user] as second argument of this useEffect. You should be good!

2020-11-11 01:14 UTC, riz671 approved these changes
Looking good. Way to go!

2020-11-11 01:15 UTC, merged